{{- if .Values.secret.enable }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ms.Name }}-secret
  namespace:  {{ .Values.namespace }}
type: "kubernetes.io/storageos"
data:
  apiAddress: {{ default "" .Values.api.address | b64enc | quote }}
  apiUsername: {{ default "" .Values.api.username | b64enc | quote }}
  apiPassword: {{ default "" .Values.api.password | b64enc | quote }}

{{- end }}